name: Deploy

# TODO: The following items should be updated :
# - Secrets, Variables, Environment Variables
# - Deployment Environments

on:
  push:
    branches:
      - develop
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  dev:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.AWS_DEV_STATE_BUCKET }}" \
            -backend-config="key=dev/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.AWS_DEV_LOCK_TABLE }}" \
            -backend-config="workspace_key_prefix=${{ vars.WORKSPACE_KEY_PREFIX }}"

      - name: Select or Create Workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Plan
        run: terraform plan -var-file=environments/dev.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan

  qa:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.QA_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.AWS_QA_STATE_BUCKET }}" \
            -backend-config="key=qa/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.AWS_QA_LOCK_TABLE }}" \
            -backend-config="workspace_key_prefix=${{ vars.WORKSPACE_KEY_PREFIX }}"

      - name: Select or Create Workspace
        run: terraform workspace select qa || terraform workspace new qa

      - name: Terraform Plan
        run: terraform plan -var-file=environments/qa.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan

  approval_preprod:
    runs-on: ubuntu-latest
    needs: qa
    environment:
      name: preprod
    steps:
      - run: echo "Preprod approval granted"

  preprod:
    runs-on: ubuntu-latest
    needs: approval_preprod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PREPROD_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.AWS_PREPROD_STATE_BUCKET }}" \
            -backend-config="key=preprod/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.AWS_PREPROD_LOCK_TABLE }}" \
            -backend-config="workspace_key_prefix=${{ vars.WORKSPACE_KEY_PREFIX }}"

      - name: Select or Create Workspace
        run: terraform workspace select preprod || terraform workspace new preprod

      - name: Terraform Plan
        run: terraform plan -var-file=environments/preprod.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan

  approval_prod:
    runs-on: ubuntu-latest
    needs: preprod
    environment:
      name: prod
    steps:
      - run: echo "Prod approval granted"

  prod:
    runs-on: ubuntu-latest
    needs: approval_prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PROD_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.AWS_PROD_STATE_BUCKET }}" \
            -backend-config="key=prod/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.AWS_PROD_LOCK_TABLE }}" \
            -backend-config="workspace_key_prefix=${{ vars.WORKSPACE_KEY_PREFIX }}"

      - name: Select or Create Workspace
        run: terraform workspace select prod || terraform workspace new prod

      - name: Terraform Plan
        run: terraform plan -var-file=environments/prod.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan